name: Check Markdown links

on:
  workflow_dispatch:
  push:
    branches:
      - main
      - bala/fix_broken_links
  schedule:
    - cron: "0 0 1 * *"

jobs:
  markdown-link-check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - uses: tcort/github-action-markdown-link-check@v1
        with:
          use-quiet-mode: 'yes'
          use-verbose-mode: 'yes'
